controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mec_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint

mec_drive_controller:
  ros__parameters:
    reference_timeout: 0.9
    use_stamped_vel: false
    command_topic: "/cmd_vel"  # Add this to specify the input topic
    odom_topic: "/odom"        # Add this to specify the odometry topic
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "back_right_wheel_joint"
    rear_left_wheel_command_joint_name: "back_left_wheel_joint"
    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.076
      sum_of_robot_center_projection_on_X_Y_axis: 0.775
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    publish_odom: true
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]